-- ══════════════════════════════════════════════════════════════════
-- CUTM Freshers 2026 — Supabase Database Schema (DDL)
-- Safe for GitHub: Contains ZERO passwords, PINs, or credentials.
-- Paste into: Supabase Dashboard -> SQL Editor -> Run
-- ══════════════════════════════════════════════════════════════════

-- 1. Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roll_no TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  qr_token TEXT UNIQUE NOT NULL,
  email_sent BOOLEAN DEFAULT FALSE,
  entry_scanned BOOLEAN DEFAULT FALSE,
  entry_scanned_at TIMESTAMPTZ,
  entry_scanned_by TEXT,
  food_scanned BOOLEAN DEFAULT FALSE,
  food_scanned_at TIMESTAMPTZ,
  food_scanned_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for rapid scanning & lookup performance
CREATE INDEX IF NOT EXISTS idx_students_qr_token ON public.students (qr_token);
CREATE INDEX IF NOT EXISTS idx_students_roll_no ON public.students (roll_no);

-- 2. Create Config Table (Stores dynamic settings configured via Admin UI)
CREATE TABLE IF NOT EXISTS public.config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Row Level Security (RLS) Configuration
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for students"
ON public.students FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all operations for config"
ON public.config FOR ALL USING (true) WITH CHECK (true);
